<?xml version="1.0"?>
<robot name="continuous_pendulum"
       xmlns:xi="http://www.w3.org/2001/XInclude"
       xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
       xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
       xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
       xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:xacro="http://ros.org/wiki/xacro"
       xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics">


  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="base_width" value="0.5" />
  <xacro:property name="base_length" value="0.7" />
  <xacro:property name="base_height" value="0.1" />
  <xacro:property name="top_offset" value="0.5" /> <!-- top shelf offset from base -->
  <xacro:property name="top_width" value="0.5" />
  <xacro:property name="top_length" value="0.7" />
  <xacro:property name="top_height" value="0.1" />
  <xacro:property name="wheel_radius" value="0.05" />
  <xacro:property name="wheel_width" value="0.01" />
  <xacro:property name="wheel_offset" value="0.02" />

  <link name="base">
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 0" /> 
      <inertia  ixx="0.1" ixy="0.0"  ixz="0.0"  iyy="0.1"  iyz="0.0"  izz="0.1" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${base_height/2+wheel_radius*2+0.01}" rpy="0 0 0" />
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2+wheel_radius*2+0.01}" rpy="0 0 0" />
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="base">
    <mu1>10</mu1>
    <mu2>10</mu2>
    <material>Gazebo/Blue</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <joint name="base_top_joint" type="fixed" >
    <origin xyz="0 0 ${top_offset}" rpy="0 0 0"/>
    <parent link="base" />
    <child link="top" />
  </joint>
  <link name="top">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" /> 
      <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${top_height/2+wheel_radius*2+0.01}" rpy="0 0 0" />
      <geometry>
        <box size="${top_length} ${top_width} ${top_height}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${top_height/2+wheel_radius*2+0.01}" rpy="0 0 0" />
      <geometry>
        <box size="${top_length} ${top_width} ${top_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="top">
    <mu1>10</mu1>
    <mu2>10</mu2>
    <material>Gazebo/Green</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <joint name="handle_joint" type="fixed" >
    <origin xyz="${-top_length/2-0.1} 0 ${top_height/2+wheel_radius*2+0.11}" rpy="0 0 0"/>
    <parent link="top" />
    <child link="handle" />
  </joint>
  <link name="handle">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" /> 
      <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="0.02" length="${top_width}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="0.02" length="${top_width}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="handle">
    <mu1>10</mu1>
    <mu2>10</mu2>
    <material>Gazebo/BumpyMetal</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>



  <joint name="front_right_caster" type="continuous" >
    <origin xyz="${base_length/2-0.025} ${base_width/2-0.025} ${wheel_radius*2+0.005}" rpy="0 0 0"/>
    <parent link="base" />
    <child link="front_right_caster" />
    <axis xyz="0 0 1" />
  </joint>
  <link name="front_right_caster">
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 0" /> 
      <inertia  ixx="0.1" ixy="0.0"  ixz="0.0"  iyy="0.1"  iyz="0.0"  izz="0.1" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${top_offset/2+0.0025}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="0.025" length="${top_offset+0.005}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${top_offset/2+0.0025}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="0.025" length="${top_offset+0.005}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="front_right_caster">
    <mu1>10</mu1>
    <mu2>10</mu2>
    <material>Gazebo/Red</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>


  <joint name="front_left_caster" type="continuous" >
    <origin xyz="${base_length/2-0.025} ${-base_width/2+0.025} ${wheel_radius*2+0.005}" rpy="0 0 0"/>
    <parent link="base" />
    <child link="front_left_caster" />
    <axis xyz="0 0 1" />
  </joint>
  <link name="front_left_caster">
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 0" /> 
      <inertia  ixx="0.1" ixy="0.0"  ixz="0.0"  iyy="0.1"  iyz="0.0"  izz="0.1" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${top_offset/2+0.0025}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="0.025" length="${top_offset+0.005}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${top_offset/2+0.0025}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="0.025" length="${top_offset+0.005}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="front_left_caster">
    <mu1>10</mu1>
    <mu2>10</mu2>
    <material>Gazebo/Red</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <joint name="front_right_wheel" type="continuous" >
    <origin xyz="${-wheel_offset} 0 ${-wheel_radius-0.005}" rpy="0 0 0"/>
    <parent link="front_right_caster" />
    <child link="front_right_wheel" />
    <axis xyz="0 1 0" />
  </joint>
  <link name="front_right_wheel">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" /> 
      <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="front_right_wheel">
    <dampingFactor>0.01</dampingFactor>
    <mu1>10</mu1>
    <mu2>10</mu2>
    <material>Gazebo/Green</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <joint name="front_left_wheel" type="continuous" >
    <origin xyz="${-wheel_offset} 0 ${-wheel_radius-0.005}" rpy="0 0 0"/>
    <parent link="front_left_caster" />
    <child link="front_left_wheel" />
    <axis xyz="0 1 0" />
  </joint>
  <link name="front_left_wheel">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" /> 
      <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="front_left_wheel">
    <dampingFactor>0.01</dampingFactor>
    <mu1>10</mu1>
    <mu2>10</mu2>
    <material>Gazebo/Green</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>



  <joint name="back_right_caster" type="continuous" >
    <origin xyz="${-base_length/2+0.025} ${base_width/2-0.025} ${wheel_radius*2+0.005}" rpy="0 0 0"/>
    <parent link="base" />
    <child link="back_right_caster" />
    <axis xyz="0 0 1" />
  </joint>
  <link name="back_right_caster">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" /> 
      <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${top_offset/2+0.0025}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="0.025" length="${top_offset+0.005}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${top_offset/2+0.0025}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="0.025" length="${top_offset+0.005}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="back_right_caster">
    <mu1>10</mu1>
    <mu2>10</mu2>
    <material>Gazebo/Red</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>


  <joint name="back_left_caster" type="continuous" >
    <origin xyz="${-base_length/2+0.025} ${-base_width/2+0.025} ${wheel_radius*2+0.005}" rpy="0 0 0"/>
    <parent link="base" />
    <child link="back_left_caster" />
    <axis xyz="0 0 1" />
  </joint>
  <link name="back_left_caster">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" /> 
      <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${top_offset/2+0.0025}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="0.025" length="${top_offset+0.005}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${top_offset/2+0.0025}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="0.025" length="${top_offset+0.005}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="back_left_caster">
    <mu1>10</mu1>
    <mu2>10</mu2>
    <material>Gazebo/Red</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <joint name="back_right_wheel" type="continuous" >
    <origin xyz="${-wheel_offset} 0 ${-wheel_radius-0.005}" rpy="0 0 0"/>
    <parent link="back_right_caster" />
    <child link="back_right_wheel" />
    <axis xyz="0 1 0" />
  </joint>
  <link name="back_right_wheel">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" /> 
      <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="back_right_wheel">
    <dampingFactor>0.01</dampingFactor>
    <mu1>10</mu1>
    <mu2>10</mu2>
    <material>Gazebo/Green</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <joint name="back_left_wheel" type="continuous" >
    <origin xyz="${-wheel_offset} 0 ${-wheel_radius-0.005}" rpy="0 0 0"/>
    <parent link="back_left_caster" />
    <child link="back_left_wheel" />
    <axis xyz="0 1 0" />
  </joint>
  <link name="back_left_wheel">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" /> 
      <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="back_left_wheel">
    <dampingFactor>0.01</dampingFactor>
    <mu1>10</mu1>
    <mu2>10</mu2>
    <material>Gazebo/Green</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

</robot>
